---
title: "00.01.VRIIntersectFiles"
author: "Nicole Barker"
date: "Last run: Nov 29, 2017"
output: 
  word_document:
    reference_docx: ../styles/ReportFormat_1.docx
---

## Background
On Nov 28, 2017, Trish sent me intersections between the latest avian data and the BC VRI dataset. 

1. bc_atlas_ident.csv
2. bcbbs_ident.csv
3. bcwsi_ident.csv

This file inspects and merges those files. 

``` {r setup, echo=F, message=F, warning=F}
require(knitr)
opts_knit$set(root.dir = '..')
```

### Load 3 datasets and subset for common, essential columns. 
Also reorder the columns to a consistent set. 
``` {r}
#ATLAS
df.bcatlas <- read.csv("data/bc_atlas_ident.csv")
colnames(df.bcatlas)[which(colnames(df.bcatlas) %in% c("DecimalLatitude", "DecimalLongitude"))] <- c("POINT_Y", "POINT_X")
columnstocut <- c("OBJECTID", "FID_BC_BCCA_SelectedMigLayer", "GeodeticDatum", "Check", "Check2", "Check3")
df.bcatlas <- df.bcatlas[-which(colnames(df.bcatlas) %in% columnstocut)]

#BBS
df.bcbbs <- read.csv("data/bcbbs_ident.csv")
columnstocut <- c("OBJECTID", "FID_XYBC_BBS_v3", "route", "Stop", "source", "comment201", "comment", "Jurs", "JursAlpha", "Country", "DATABASE", "source_1", "origin_may3")
df.bcbbs <- df.bcbbs[-which(colnames(df.bcbbs) %in% columnstocut)]

#WSI
df.bcwsi <- read.csv("data/bcwsi_ident.csv")
columnstocut <- c("OBJECTID", "FID_BAMNATV4BConly", "Country", "StateProvi", "DecimalLat", "DecimalLon", "GeodeticDa")
df.bcwsi <- df.bcwsi[-which(colnames(df.bcwsi) %in% columnstocut)]
```

``` {r}
pt.atlas <- df.bcatlas[c("PCODE", "SS", "POINT_X", "POINT_Y")]
pt.bbs <- df.bcbbs[1:17]
pt.wsi <- df.bcwsi[c("PCODE", "SS", "POINT_X", "POINT_Y")]

write.table(pt.atlas, "data/pt.atlas.csv", sep=",", row.names=F, col.names=T)
write.table(pt.bbs, "data/pt.bbs.csv", sep=",", row.names=F, col.names=T)
write.table(pt.wsi, "data/pt.wsi.csv", sep=",", row.names=F, col.names=T)
```


### Combine (rbind) 3 datasets
``` {r}
df.bcbirds <- (df.bcbbs, df.bcatlas, by="")
```
